import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Xylem Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
      <title>Xylem Ecommerce</title>
      <link
  rel="preload"
  as="image"
  href="/images/img_hero.jpg"
  fetchPriority="high"
/>
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
